<?php

function olckb_theme ($existing, $type, $theme, $path) {
 
  $path = drupal_get_path('module', 'olckb');

  $theme_base = array(
    'path' => $path . '/theme',
  );
 
  return array(

    'olckb_js_template' => $theme_base + array(
      'variables' => array('olckb_chars' => NULL),
      'template' => 'olckb-js-template',
    ),

  );
  
}


// block
function olckb_block_info() {

  // Default block settings
  $defaults = array(
    'status' => TRUE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'weight' => 0,
    'region' => BLOCK_REGION_NONE,
  );
  
  // Defining blocks
  $blocks['olckb_toolbar'] = $defaults + array(
    'info' => t('OLC Keyboard Toolbar')
  );
  
  return $blocks;
  
}

function olckb_block_configure($block_name = '') {

  return array();

}

function olctkb_block_save($block_name = '', $values = array()) {
}

function olckb_block_view($block_name = '') {
  switch ($block_name) {
    case 'olckb_toolbar':
      return _olckb_block_toolbar_view();
      break;
    default:
      // Block name unknown
      return NULL;
      break;
  }
}

function _olckb_block_toolbar_view() {
  return array(
    'subject' => 'Textbook options',
    'content' => array(
      '#markup' => theme(
        'olckb_js_template', array('olckb_chars' => _olckb_chars())
      )
    ),
  );
}

function olckb_page_build(&$page) {
  include drupal_get_path('module', 'olckb') . '/olckb_data.php';
  $page['page_top']['olckb'] = array(
    '#markup' => theme(
      'olckb_js_template', 
      array('olckb_chars' => _olckb_chars())
    ),
  );
}

function _olckb_chars() {

  include drupal_get_path('module', 'olckb') . '/olckb_data.php';

  // Provision "type" key
  foreach ($olckb_characters as $kb_index => $kb_item) {

    $default_type = 'CharacterGroup';
    if (empty($kb_item['type'])) {
      $kb_item['type'] = $default_type;
    }
    else {
      // pass; already defined
    }

  }

  // Normalize characters
  foreach ($olckb_characters as $kb_index => $kb_item) {

    if ($kb_item['type'] == 'CharacterGroup') {

      foreach ($kb_item['characters'] as $char_index => $char) {

        $char_normalized = null;
        switch (gettype($char)) {
          case 'array':
            
            $olckb_characters[$kb_index]['characters'][$char_index]['show'] = _olckb_normalize($char['show']);
            $olckb_characters[$kb_index]['characters'][$char_index]['insert'] = _olckb_normalize($char['insert']);

            break;
          case 'string':

            $olckb_characters[$kb_index]['characters'][$char_index] = _olckb_normalize($char);

            break;
          default:

            // pass

            break;
        }
        

      }

    }
    else {
      // pass
    }

  }

  return $olckb_characters;

}

function _olckb_normalize($value) {

  return ! Normalizer::isNormalized($value)
         ? Normalizer::normalize($value, Normalizer::FORM_KC)
         : $value
         ;

}

