<?php

function olckb_theme ($existing, $type, $theme, $path) {
 
  $path = drupal_get_path('module', 'olckb');
  $base = array(
    'path' => $path . '/theme',
  );
 
  return array(
    'olckb_js_template' => $base + array(
      'variables' => array('olckb_chars' => NULL),
      'template' => 'olckb-js-template',
    ),
  );
  
}

// block
function olckb_block_info() {

  // Default block settings
  $defaults = array(
    'status' => TRUE,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'weight' => 0,
    'region' => BLOCK_REGION_NONE,
  );
  
  // Defining blocks
  $blocks['olckb_toolbar'] = $defaults + array(
    'info' => t('OLC Keyboard Toolbar')
  );
  
  return $blocks;
  
}

function olckb_block_configure($block_name = '') {
  return array();
}

function olctkb_block_save($block_name = '', $values = array()) {
}

function olckb_block_view($block_name = '') {
  switch ($block_name) {
    case 'olckb_toolbar':
      return _olckb_block_toolbar_view();
      break;
    default:
      // Block name unknown
      return NULL;
      break;
  }
}

function _olckb_block_toolbar_view() {
  return array(
    'subject' => 'Textbook options',
    'content' => array(
      '#markup' => theme(
        'olckb_js_template', array('olckb_chars' => _olckb_chars())
      )
    ),
  );
}

function olckb_page_build(&$page) {
  include drupal_get_path('module', 'olckb') . '/olckb_data.php';
  $page['page_top']['olckb'] = array(
    '#markup' => theme(
      'olckb_js_template', 
      array('olckb_chars' => _olckb_chars())
    ),
  );
}

function _olckb_chars() {
  include drupal_get_path('module', 'olckb') . '/olckb_data.php';
  foreach ($olckb_characters as $group_index => $group) {
    foreach ($group['characters'] as $char_index => $char) {
      if (!Normalizer::isNormalized($char)) {
        $olckb_characters[$group_index]['characters'][$char_index] = Normalizer::normalize( Normalizer::FORM_KC);
      }
      else {
        // Skip; already normalized
      }
    }
  }
  return $olckb_characters;
}


